# Generated by Django 2.2.7 on 2020-02-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20200121_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_file',
            name='fname',
        ),
    ]
