# Generated by Django 3.0.3 on 2020-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_remove_upload_file_fname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_File',
        ),
    ]
